import { useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { toast } from 'sonner';
import { Session, ConnectionResult, CommandResponse, SavedSession, LogEntry } from "../types";

// Define the arguments for the connect function
export interface ConnectConfig {
    host: string;
    port: number;
    username: string;
    password: string;
    privateKeyPath?: string | null;
    sessionName: string;
    termType?: string;
    remoteCommand?: string;
    backspaceMode?: string;
}

export interface UseTerminalConnectionProps {
    addLog: (sessionId: string, message: string, level: LogEntry["level"], source: LogEntry["source"]) => void;
    saveSession: (session: SavedSession) => Promise<SavedSession | undefined>;
    addToRecent: (id: string) => Promise<void>;
}

export function useTerminalConnection({ addLog, saveSession, addToRecent }: UseTerminalConnectionProps) {
    const [activeSessions, setActiveSessions] = useState<Session[]>([]);
    const [activeSessionId, setActiveSessionId] = useState<string | null>(null);
    const [connectionStatus, setConnectionStatus] = useState<"disconnected" | "connecting" | "connected">("disconnected");
    const [statusMessage, setStatusMessage] = useState("Disconnected");

    const derivedActiveSession = activeSessions.find(s => s.id === activeSessionId);

    const updateSessionView = (sessionId: string, view: Session["activeView"]) => {
        setActiveSessions((prev) =>
            prev.map((s) => (s.id === sessionId ? { ...s, activeView: view } : s))
        );
    };

    /**
     * Connects to an SSH server.
     * Returns true if connected successfully, false otherwise.
     * Throws an error object if authentication fails explicitly so the UI can prompt.
     */
    const connect = async (
        config: ConnectConfig,
        saveForLater?: boolean,
        addToFav?: boolean
    ): Promise<boolean> => {
        setConnectionStatus("connecting");
        setStatusMessage(`Connecting to ${config.host}...`);

        try {
            const response = await invoke<CommandResponse<ConnectionResult>>("ssh_connect", {
                params: {
                    host: config.host,
                    port: config.port,
                    username: config.username,
                    password: config.password || null,
                    private_key_path: config.privateKeyPath || null,
                    session_name: config.sessionName || `${config.username}@${config.host}`,
                    term_type: config.termType || null,
                    remote_command: config.remoteCommand || null,
                },
            });

            if (response.success && response.data) {
                const newSession: Session = {
                    id: response.data.session_id,
                    name: config.sessionName || `${config.username}@${config.host}`,
                    host: config.host,
                    port: config.port,
                    username: config.username,
                    connected: true,
                    activeView: "terminal",
                    backspaceMode: config.backspaceMode,
                };
                setActiveSessions((prev) => [...prev, newSession]);
                setActiveSessionId(newSession.id);
                setConnectionStatus("connected");
                setStatusMessage(`Connected to ${config.username}@${config.host}`);

                addLog(newSession.id, `Connected to ${response.data.host}`, "success", "SSH");
                if (response.data.banner) addLog(newSession.id, `Banner: ${response.data.banner}`, "info", "SSH");

                // Save session for later if requested
                if (saveForLater) {
                    try {
                        const savedSession = await saveSession({
                            id: "", // uuid generated by backend
                            name: config.sessionName || `${config.username}@${config.host}`,
                            host: config.host,
                            port: config.port,
                            username: config.username,
                            auth_type: config.privateKeyPath ? "privatekey" : "password",
                            private_key_path: config.privateKeyPath || undefined,
                            is_favorite: addToFav || false,
                            backspace_mode: config.backspaceMode,
                            password: config.password, // Save password if provided
                        } as SavedSession); // simplified cast, saveSession usually handles ID generation

                        // Add to recent after saving
                        if (savedSession?.id) {
                            addToRecent(savedSession.id);
                        }
                    } catch (err) {
                        console.error("Failed to save session:", err);
                        toast.error("Failed to save session for later");
                    }
                }
                return true;
            } else {
                setConnectionStatus("disconnected");
                setStatusMessage(`Failed: ${response.error}`);
                const errStr = response.error || "";
                toast.error(`Connection failed: ${errStr}`);

                // Throw specific error for auth handling
                if ((errStr.includes("No authentication method provided") || errStr.includes("Authentication failed") || errStr.toLowerCase().includes("auth")) && !config.password && !config.privateKeyPath) {
                    throw new Error("AUTH_REQUIRED");
                }
                return false;
            }
        } catch (error) {
            const errStr = String(error);
            if (errStr === "Error: AUTH_REQUIRED") {
                throw error; // Re-throw our specific error
            }

            setConnectionStatus("disconnected");
            setStatusMessage(`Error: ${error}`);
            toast.error(`Connection error: ${error}`);

            if ((errStr.includes("No authentication method provided") || errStr.includes("Authentication failed")) && !config.password && !config.privateKeyPath) {
                throw new Error("AUTH_REQUIRED");
            }
            return false;
        }
    };

    const disconnect = async (sessionId: string) => {
        try {
            await invoke<CommandResponse<void>>("ssh_disconnect", { sessionId });
            setActiveSessions((prev) => prev.filter((s) => s.id !== sessionId));
            if (activeSessionId === sessionId) {
                setActiveSessionId(null);
                setConnectionStatus("disconnected");
                setStatusMessage("Disconnected");
            }
        } catch (error) {
            console.error("Disconnect error:", error);
            toast.error(`Disconnect failed: ${error}`);
        }
    };

    return {
        activeSessions,
        activeSessionId,
        setActiveSessionId,
        connectionStatus,
        statusMessage,
        derivedActiveSession,
        updateSessionView,
        connect,
        disconnect
    };
}
